/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serenegiant_opencvusageproject_OpenCVHelper */

#ifndef _Included_com_serenegiant_opencvusageproject_OpenCVHelper
#define _Included_com_serenegiant_opencvusageproject_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serenegiant_opencvusageproject_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_serenegiant_opencvusageproject_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_serenegiant_opencvusageproject_OpenCVHelper
 * Method:    convertMat
 * Signature: (JII)[I
 */
JNIEXPORT void JNICALL Java_com_serenegiant_opencvusageproject_OpenCVHelper_convertMat
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
